# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "552e36fc7694e73dfa13c65d421f4f4f"
application_url = "https://gary-log-vitamins-sky.trycloudflare.com"
embedded = true
name = "product page"
handle = "product-page-7"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gary-log-vitamins-sky.trycloudflare.com/auth/callback",
  "https://gary-log-vitamins-sky.trycloudflare.com/auth/shopify/callback",
  "https://gary-log-vitamins-sky.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "tigerbis.myshopify.com"
automatically_update_urls_on_dev = true
